"""make fields nullable

Revision ID: 21562d71fa25
Revises: 2c655099dbde
Create Date: 2026-07-22 11:53:29.709585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21562d71fa25'
down_revision: Union[str, Sequence[str], None] = '2c655099dbde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('invoices', 'source_format',
               existing_type=postgresql.ENUM('PDF', 'EXCEL', 'IMAGE', name='source_format'),
               nullable=True)
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.alter_column('invoices', 'source_format',
               existing_type=postgresql.ENUM('PDF', 'EXCEL', 'IMAGE', name='source_format'),
               nullable=False)
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
